config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[ show edit ]

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to flats_path, notice: "Flat was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<h1>Editing flat</h1>

<%= render "form", flat: @flat %>

<br>

<div>
  <%= link_to "Back to flats", flats_path %>
</div>

app/views/flats/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Simple Airbnb</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="ms-auto flex">
        <a class="btn btn-outline-primary my-2 my-sm-0 ms-2" href="/flats/new">Add Flat</a>
      </div>
    </div>
  </div>
</nav>

<br />

<%= notice %>


<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All our Flats (<%= @flats.count %>)</h1>
    </div>
  </div>

  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-md-4">
        <div class="flat-card">
          <div class="flat-card-image" style="background-image: url('https://image.noelshack.com/fichiers/2022/46/3/1668607583-jean-gui-le-male.jpg')"></div>
          <div class="flat-card-content">
            <div class="flat-card-title">
              <h4><%= flat.name %></h4>
            </div>
            <p><%= flat.address %></p>
            <div class="flex">
              <div class="flex align-items-center">
                <i class="fa-solid fa-people-line"></i>
                <span><%= flat.number_of_guests %></span>
              </div>
              <div class="flex align-items-center ms-3">
                <i class="fa-solid fa-euro-sign"></i>
                <span><%= flat.price_per_night %></span>
              </div>
            </div>
          </div>
          <div class="flat-card-actions">
            <%= link_to "More info", flat %>
            <%= link_to "Edit", edit_flat_path(flat) %>
            <a data-turbo-method="delete" data-turbo-confirm="Are you sure?" class="ms-3 text-danger" href="/flats/6507">Remove</a>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<h1>New Flat</h1>

<%= render "form", flat: @flat %>

<br>

<div>
  <%= link_to "Back to flats", flats_path %>
</div>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>
<h4><%= @flat.address %></h4>
<p><%= @flat.description %></p>
<i class="fa-solid fa-people-line"></i>
<span><%= @flat.number_of_guests %></span>
<i class="fa-solid fa-euro-sign"></i>
<span><%= @flat.price_per_night %></span>

<p><%= link_to "Back to homepage", flats_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>